#!/usr/bin/env bash
# Render the documentation site into site/.
#
#   bash .github/scripts/build-docs-site.sh
#
# Lives here rather than in the shared scripts folder because the docs workflow
# runs from a checkout of this repository alone and cannot reach anything
# outside it. Runs locally too, for previewing before pushing.
#
# The site is docs/*.md rendered by pandoc plus the API reference under /api/,
# generated by YARD from the comments in lib/. The reference is part of the site
# rather than an afterthought: this gem is not on rubygems.org yet, so nothing
# else hosts one, and generating it from the same commit as the prose is what
# stops the two drifting apart.
#
# The README is deliberately *not* the front page any more. A README is written
# for somebody looking at a repository — badges, build instructions, a status
# note — and a documentation site is written for somebody trying to use the
# library. One document cannot be both without being worse at each, and the
# badges in particular have no business on a rendered page: they are images
# fetched from a third party on every view, saying things a site visitor did not
# ask about. docs/index.md is the front page, and it is written for that job.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO_ROOT"
OUT="site"

command -v pandoc >/dev/null || { echo "pandoc is required" >&2; exit 1; }

# The same question as the link check at the bottom of this script, asked of the
# source instead of the site.
#
# Links between pages are written as .md and rewritten to .html further down,
# for the rendered copy only. That convention exists so the same files read
# correctly on GitHub, which is where somebody meets these pages before they
# find the site — and the check at the bottom cannot see that half. It runs on
# the rewritten output, so it is satisfied by `guide.html` existing in site/
# whatever the markdown said. A link that is wrong in the source and right after
# rewriting is invisible to it in principle, not by oversight, and this family
# of repositories has shipped exactly that: cross-page links written as .html,
# dead in GitHub's markdown view and green in every build.
#
# It runs first because it needs neither pandoc nor YARD, and a bad link is
# cheapest to find before a minute of rendering.
python3 - <<'PY'
import os, re, sys, urllib.parse

DOCS = "docs"

pages = sorted(f for f in os.listdir(DOCS) if f.endswith(".md"))
broken = []
links = 0

for page in pages:
    with open(os.path.join(DOCS, page), encoding="utf-8") as handle:
        body = handle.read()
    for target in re.findall(r"\]\(([^)\s]+)\)", body):
        if target.startswith(("http://", "https://", "mailto:", "#")):
            continue
        path = urllib.parse.unquote(target.partition("#")[0])
        if not path:
            continue
        links += 1
        # The generated API reference is genuinely HTML: YARD writes it into
        # site/api, no markdown renders into it, and it is .html on GitHub and
        # on the site alike. Any other .html target is a docs page written the
        # wrong way round — it is the mistake this check exists for, so it is
        # named as that rather than reported as a missing file.
        if path.endswith(".html"):
            if not path.startswith("api/"):
                broken.append("{} -> {}  (a docs page link belongs in .md)".format(page, target))
            continue
        if not os.path.exists(os.path.join(DOCS, path)):
            broken.append("{} -> {}".format(page, target))

if broken:
    print("::error::docs/ links that are dead when the pages are read on GitHub:")
    for item in broken:
        print("  " + item)
    sys.exit(1)
print("{} source pages, {} internal links, every one resolves inside docs/"
      .format(len(pages), links))
PY

# The option was renamed: --highlight-style in older pandoc,
# --syntax-highlighting in newer, and each rejects or deprecates the other.
# Ubuntu's package and a current Homebrew install sit on opposite sides of that
# change, so the flag is chosen rather than assumed — hardcoding either one
# breaks the build somewhere.
if pandoc --help 2>&1 | grep -q -- '--syntax-highlighting'; then
  HIGHLIGHT=(--syntax-highlighting=tango)
else
  HIGHLIGHT=(--highlight-style=tango)
fi

rm -rf "$OUT"
mkdir -p "$OUT"

# Images as well as stylesheets. Copying only *.css is how a logo ends up
# referenced by every page and served by none.
if compgen -G "docs/assets/*" > /dev/null; then
  mkdir -p "$OUT/assets"
  cp docs/assets/* "$OUT/assets/"
fi

# The site ships the text it is published under, beside the pages rather than
# only in the repository. Copied as it is: a licence rendered to HTML is a
# licence somebody has reformatted.
#
# The licence page used to link to this copy by a bare relative path, which
# resolved on the site and 404'd for anyone reading docs/licence.md on GitHub —
# the exact defect the source-side link check above now catches. It links to the
# file in the repository instead, which is right in both readings; a path back
# up out of site/ would not be, because Pages serves this under a project
# subdirectory.
cp LICENSE "$OUT/LICENSE"

cat > "$OUT/style.css" <<'CSS'
:root {
  color-scheme: light dark;
  --fg:#1a1a1a; --bg:#fff; --muted:#5f5f5f; --line:#e4e4e4;
  --accent:#b4451f; --code-bg:#f7f7f5; --nav-bg:#fbfbfa;
}
@media (prefers-color-scheme: dark) {
  :root { --fg:#e8e8e8; --bg:#161616; --muted:#9c9c9c; --line:#2d2d2d;
          --accent:#ff8a5c; --code-bg:#1e1e1e; --nav-bg:#1b1b1b; }
}
* { box-sizing:border-box; }
body { margin:0; background:var(--bg); color:var(--fg);
       font:16px/1.7 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif; }
nav.top { background:var(--nav-bg); border-bottom:1px solid var(--line);
          padding:.85rem 1.25rem; display:flex; gap:1.15rem; flex-wrap:wrap; align-items:baseline;
          position:sticky; top:0; z-index:10; }
nav.top .brand { display:inline-flex; align-items:center; gap:.5rem; font-weight:700;
                 letter-spacing:-.01em; margin-right:.5rem; }
nav.top .brand img { height:22px; width:auto; display:block; }
/* The mark is black on transparent, so it disappears against a dark page.
   Inverting is enough for a two-tone logo and avoids shipping a second file. */
@media (prefers-color-scheme: dark) { nav.top .brand img { filter: invert(1) brightness(1.15); } }
nav.top a { color:var(--fg); text-decoration:none; font-size:.9rem; opacity:.78; }
nav.top a:hover { opacity:1; color:var(--accent); }
/* The right-hand group: the destinations somebody arrives looking for, rather
   than the page-by-page guide. The first enterprise link carries the auto
   margin, so the group stays together however many guide entries are added to
   its left. */
nav.top a.tutorials { color:var(--accent); opacity:1; font-weight:600; }
nav.top a.api { color:var(--accent); opacity:1; font-weight:600; }
nav.top a.enterprise { color:var(--fg); opacity:.78; }
nav.top a.enterprise:hover { opacity:1; color:var(--accent); }

/* Grouped navigation. No JavaScript: the menu opens on hover and on focus-within,
   so a keyboard reaches it and a blocked script cannot break it. */
nav.top .group { position:relative; display:inline-block; }
nav.top .group > button { font:inherit; font-size:.9rem; color:var(--fg); opacity:.78;
  background:none; border:0; padding:0; cursor:pointer; }
nav.top .group > button::after { content:" \25be"; font-size:.8em; opacity:.7; }
nav.top .group:hover > button, nav.top .group:focus-within > button {
  opacity:1; color:var(--accent); }
nav.top .group .menu { display:none; position:absolute; left:0; top:100%; z-index:20;
  background:var(--nav-bg); border:1px solid var(--line); border-radius:8px;
  padding:.4rem 0; min-width:15rem; box-shadow:0 6px 24px rgba(0,0,0,.12); }
nav.top .group:hover .menu, nav.top .group:focus-within .menu { display:block; }
nav.top .group .menu a { display:block; padding:.35rem 1rem; opacity:.85; white-space:nowrap; }
nav.top .group .menu a:hover { background:var(--code-bg); opacity:1; }
nav.top a.enterprise:first-of-type { margin-left:auto; }

/* On a narrow screen the menus would hang off the edge, so everything unfolds
   into a list instead of pretending to be a menu bar. */
@media (max-width: 900px) {
  nav.top { flex-wrap:wrap; }
  nav.top .group { position:static; }
  nav.top .group .menu { position:static; display:block; border:0; box-shadow:none;
    padding:0; background:none; min-width:0; }
  nav.top .group > button { display:none; }
  nav.top .group .menu a { display:inline-block; padding:0; }
  nav.top a.enterprise:first-of-type { margin-left:0; }
}
main { max-width:50rem; margin:0 auto; padding:2.5rem 1.25rem 5rem; }
h1,h2,h3 { line-height:1.25; letter-spacing:-.015em; }
h1 { font-size:2.1rem; margin:0 0 1.5rem; }
h2 { font-size:1.5rem; margin:2.5rem 0 .85rem; padding-top:.6rem;
     border-top:1px solid var(--line); }
h3 { font-size:1.15rem; margin:2rem 0 .6rem; }
p, li { color:var(--fg); }
a { color:var(--accent); }
pre { background:var(--code-bg); padding:1rem 1.1rem; border-radius:8px; overflow-x:auto;
      border:1px solid var(--line); font-size:.855rem; line-height:1.55; }
code { font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; font-size:.9em; }
p code, li code, td code, th code { background:var(--code-bg); border:1px solid var(--line);
      border-radius:4px; padding:.08em .35em; color:var(--accent); }
pre code { background:none; border:none; padding:0; color:inherit; }
blockquote { margin:1.5rem 0; padding:.1rem 1.1rem; border-left:3px solid var(--line);
             color:var(--muted); }
table { border-collapse:collapse; width:100%; margin:1.5rem 0; font-size:.92rem; display:block;
        overflow-x:auto; }
th,td { border-bottom:1px solid var(--line); padding:.55rem .8rem; text-align:left;
        vertical-align:top; }
th { color:var(--muted); font-weight:600; }
img { max-width:100%; }
footer { max-width:50rem; margin:0 auto; padding:1.5rem 1.25rem 4rem;
         border-top:1px solid var(--line); color:var(--muted); font-size:.85rem; }

/* Pandoc writes its own syntax colours into a <style> block in the head, and
   they are tuned for a white page: numbers, floats and base-n literals are all
   #0000cf, which on this page's dark background is about 1.4:1 against it —
   `timedelta(seconds=1)` reads as `timedelta(seconds= )`. This stylesheet is
   linked after that block, so redefining the handful of colours that go dark
   is enough; the light palette is left exactly as pandoc chose it. */
@media (prefers-color-scheme: dark) {
  code span.dv, code span.bn, code span.fl { color:#b5cea8; }   /* literals */
  code span.st, code span.ch, code span.vs { color:#a3d18a; }   /* strings */
  code span.co, code span.cn                { color:#9c9c9c; }   /* comments */
  code span.kw, code span.cf                { color:#7fb3ff; }   /* keywords */
  code span.dt, code span.bu                { color:#7fd4c1; }   /* types */
  code span.fu                              { color:#dcb6ff; }   /* functions */
  code span.at, code span.va                { color:#e8e8e8; }
  code span.op, code span.sc                { color:#c9c9c9; }
  code span.er, code span.al                { color:#ff8a5c; }
}
CSS

# A handful of top-level entries with the rest grouped underneath, rather than
# seventeen in a row. Seventeen is legible at 1600px and wraps into three lines on
# a laptop, and a navigation nobody can scan is one nobody uses.
#
# Getting started and Tutorials are both top-level and both accented: they are the
# two doors somebody arriving at this site is looking for, and burying either one
# in a menu is how a tutorial set goes unread. The four tutorials themselves are
# reached from tutorials.html rather than from here.
#
# The groups open on hover and on focus, so the keyboard reaches them too, and
# every link is a plain anchor — the menu needs no JavaScript and still works
# when it is blocked or fails to load.
NAV='<nav class="top">
  <span class="brand"><img src="assets/acemq.png" alt="AceMQ"> for Rails</span>
  <a href="index.html">Overview</a>
  <a class="tutorials" href="getting-started.html">Getting started</a>

  <div class="group">
    <button type="button" aria-haspopup="true">Guide</button>
    <div class="menu">
      <a href="configuration.html">Configuration</a>
      <a href="publishing.html">Publishing</a>
      <a href="consumers.html">Consumers</a>
      <a href="topology.html">Topology</a>
      <a href="serialization.html">Serialization</a>
      <a href="security.html">Security</a>
      <a href="testing.html">Testing</a>
    </div>
  </div>

  <div class="group">
    <button type="button" aria-haspopup="true">Patterns</button>
    <div class="menu">
      <a href="patterns.html">Patterns from Rails</a>
      <a href="outbox.html">Transactional outbox</a>
      <a href="idempotency.html">Idempotent consumer</a>
      <a href="saga.html">Sagas</a>
      <a href="request-reply.html">Request and reply</a>
      <a href="scheduling.html">Scheduling</a>
      <a href="streams.html">Streams</a>
    </div>
  </div>

  <div class="group">
    <button type="button" aria-haspopup="true">Operations</button>
    <div class="menu">
      <a href="lifecycle.html">Shutdown and the drain</a>
      <a href="health.html">Health</a>
      <a href="observability.html">Observability</a>
      <a href="interceptors.html">Interceptors</a>
      <a href="reloading.html">Eager loading and reloading</a>
      <a href="not-activejob.html">Why not ActiveJob</a>
      <a href="licence.html">Licence</a>
    </div>
  </div>

  <a class="api" href="api/index.html">API reference</a>
  <a class="enterprise" href="https://acemq.org/acemq-ruby-amqp/">Ruby library</a>
  <a class="enterprise" href="https://acemq.org/">JVM libraries</a>
  <a class="enterprise" href="https://acemq.com">Enterprise support</a>
</nav>
<main>'

FOOT='</main>
<footer>
  <a href="https://github.com/AceMQ-Company/acemq-ruby-amqp-rails">AceMQ for Rails</a> &mdash;
  Apache-2.0, and provided without warranty &mdash; see the
  <a href="licence.html">licence</a>.
  <a href="https://acemq.com">Enterprise support</a>.
  The JVM libraries are at <a href="https://acemq.org/">acemq.org</a>.
  Pre-1.0 and in development.
  RabbitMQ, Ruby and Rails are trademarks of their respective owners. This project is not
  affiliated with either.
</footer>'

printf '%s' "$NAV" > "$OUT/.nav.html"
printf '%s' "$FOOT" > "$OUT/.foot.html"

# Without this the browser asks for /favicon.ico on every page and the server
# answers 404, which is a console error on a site that otherwise has none — and
# a console with one error in it is a console nobody reads.
cat > "$OUT/.head.html" <<'HEAD'
<link rel="icon" href="assets/acemq.png">
HEAD

for f in docs/*.md; do
  base="$(basename "${f%.md}")"
  # The first heading is the page title. pagetitle rather than title, because
  # pandoc's template renders a title block from "title" and would print a
  # second copy of the H1 the markdown already contains.
  title="$(head -n1 "$f" | sed 's/^#\{1,6\} *//')"
  # The overview's own heading is the site's name, and suffixing it produces
  # "AceMQ for Rails — AceMQ for Rails" in the browser tab.
  if [ "$title" = "AceMQ for Rails" ]; then
    pagetitle="$title"
  else
    pagetitle="$title — AceMQ for Rails"
  fi
  pandoc "$f" \
    --from=gfm --to=html5 --standalone \
    --metadata pagetitle="$pagetitle" \
    "${HIGHLIGHT[@]}" \
    --css=style.css \
    --include-in-header="$OUT/.head.html" \
    --include-before-body="$OUT/.nav.html" \
    --include-after-body="$OUT/.foot.html" \
    --output "$OUT/$base.html"
  # Links between pages are written as .md so they work when the same files are
  # read on GitHub; only the rendered copy is rewritten. The anchor is kept: a
  # link to another page's section is written .md#section and must survive.
  perl -pi -e 's{href="([^":#]*)\.md(#[^"]*)?"}{href="$1.html$2"}g' "$OUT/$base.html"
  echo "  rendered $base.html"
done

rm -f "$OUT/.nav.html" "$OUT/.foot.html" "$OUT/.head.html"

# The API reference, from the comments in lib/. Its internal links are not
# checked below: YARD generates its own frames and anchors, and checking them
# here would be this script marking another tool's homework. The badge check
# does cover it, because that failure came from here.
#
# Its front page is .github/api-index.md rather than the README. Left to itself
# YARD renders whatever it finds as README* as the reference's index, and this
# one opens with three shields.io badges — images fetched from a third party
# every time somebody opens the page, to say things nobody browsing an API
# reference came to find out.
# The path is relative on purpose: YARD resolves --readme against the project
# root and quietly falls back to README.md when handed an absolute path outside
# it, which is exactly the failure this argument exists to prevent.
if command -v yard >/dev/null; then
  yard doc --quiet --output-dir "$OUT/api" --readme .github/api-index.md --no-progress lib
else
  echo "yard is not installed; the API reference will be missing" >&2
  exit 1
fi

# A published page linking to a 404 is a failure this site family has had
# before, and it went unnoticed because nothing checked. Cheap to check, so it
# is checked. The same pass refuses a badge: the README is not rendered here any
# more, and this is what keeps it that way once somebody pastes a snippet of it
# into a page.
python3 - <<'PY'
import os, re, sys
pages = [f for f in os.listdir("site") if f.endswith(".html")]
broken, badges = [], []
for f in pages:
    body = open("site/" + f).read()
    for href in re.findall(r'href="([^"]+)"', body):
        if href.startswith(("http://", "https://", "#", "mailto:")):
            continue
        target = href.split("#")[0]
        if target and not os.path.exists(os.path.join("site", target)):
            broken.append(f"{f} -> {href}")

# Every rendered file, the generated reference included: the badges got in
# through YARD once already.
for root, _, names in os.walk("site"):
    for name in names:
        if not name.endswith(".html"):
            continue
        path = os.path.join(root, name)
        if "shields.io" in open(path, encoding="utf-8", errors="replace").read():
            badges.append(os.path.relpath(path, "site"))
if broken:
    print("::error::the site links to pages that do not exist:")
    for b in broken:
        print("  " + b)
if badges:
    print("::error::badge images reached the rendered site:")
    for b in badges:
        print("  " + b)
if broken or badges:
    sys.exit(1)
print(f"{len(pages)} pages, every internal link resolves, no badges")
PY

# Jekyll would otherwise skip anything underscore-prefixed, which is half of
# what YARD generates.
touch "$OUT/.nojekyll"

echo "Site written to $REPO_ROOT/$OUT/index.html"
